/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.Views;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.MouseEvent;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Admin
 */
public class FrmInicio extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */

    public JPanel panelLogin;
    public JPanel panelNavLogin;
    public JPanel panelWelcome;

    
    public FrmInicio() {

         
        initComponents();

        panelWelcome = new PanelWelcome();
        jPanel1.add(panelWelcome);
        panelWelcome.setBounds(150, 0, 920, 690);

        panelWelcome.setVisible(true);
        jPanel2.setVisible(false);

        //Este metodo setea el NAV_Panel dejandolo LIMPIO sin NADA Seleccionado
        resetNavPanel();

        /**
         * Estableciendo TAMAÑO PERSONALIZADO para CADA PANTALLA (para que el
         * programa se adapte sea cual sea su tamaño, le aplicará relleno)
         *
         * En primer lugar establecemos los tamaños para el JFRAME, para que
         * apenas pueda redimensionarse tambien se abrirá en pantalla completa
         * directamente
         */
        //Obtenemos el tamaño de la pantalla donde estamos ejecutando  
        Dimension pantallaTamano = Toolkit.getDefaultToolkit().getScreenSize();

        this.setMinimumSize(new Dimension(1080, 720)); //Le resto 35, para que "minimize algo"
        this.setMaximumSize(new Dimension(pantallaTamano.width, pantallaTamano.height));
        this.setSize(new Dimension(pantallaTamano.width, pantallaTamano.height));

        this.setExtendedState(this.MAXIMIZED_BOTH);//Con esto le indicamos que se ejecute en modo MAXIMIZADO

        //AgregANDO nuestro PanelPrincial, al panelRelleno, endicandole la posición que lo mantendrá centrado en la pantalla
        jPanel8.add(jPanel1);
        //Al ancho de la pantalla lo divido en 2 y le resto la mitad del ancho de mi ventana, con eso queda centrada en el eje X, para el eje Y es lo mismo pero con el alto.
        jPanel1.setBounds((pantallaTamano.width / 2) - (jPanel1.getWidth() / 2), (pantallaTamano.height / 2) - 15 - (jPanel1.getHeight() / 2), 1070, 690);
//       jPanel1.setBounds(0,0 , 1070, 690);
        
   
        //Agregando panelRelleno que ya tiene el panelPrincipal añadido al Jframe indicandole su posicion y tamaño, QUE SERÁ TODO el ANCHO Y ALTO de nuestra PANTALLA
        getContentPane().add(jPanel8);
        jPanel8.setBounds(0, 0, pantallaTamano.width, pantallaTamano.height);

        pack();
        setLocationRelativeTo(null);
////////////////////////////////////////   Fin de establaciendo tamaños personalizados y centrando el Jpanel

    }//Fin del constructor

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public JButton getBtnSignIn() {
        return btnSignIn;
    }
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel8 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnSignIn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btn_3 = new javax.swing.JPanel();
        ind_3 = new javax.swing.JPanel();
        lblNavCaja = new javax.swing.JLabel();
        btn_1 = new javax.swing.JPanel();
        ind_1 = new javax.swing.JPanel();
        lblNavInicio = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(23, 35, 51));
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(1070, 690));

        jPanel8.setBackground(new java.awt.Color(51, 51, 51));
        jPanel8.setMinimumSize(new java.awt.Dimension(1070, 690));
        jPanel8.setName(""); // NOI18N
        jPanel8.setPreferredSize(new java.awt.Dimension(1124, 740));

        jPanel1.setBackground(new java.awt.Color(102, 255, 51));
        jPanel1.setForeground(new java.awt.Color(23, 35, 51));
        jPanel1.setMaximumSize(new java.awt.Dimension(1070, 690));
        jPanel1.setMinimumSize(new java.awt.Dimension(1070, 690));
        jPanel1.setPreferredSize(new java.awt.Dimension(1070, 690));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setMaximumSize(new java.awt.Dimension(920, 690));
        jPanel2.setMinimumSize(new java.awt.Dimension(920, 690));

        jLabel1.setText("Usuario:");

        jLabel2.setText("Contraseña:");

        jTextField1.setBackground(new java.awt.Color(204, 204, 204));
        jTextField1.setForeground(new java.awt.Color(0, 0, 0));
        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPasswordField1.setBackground(new java.awt.Color(204, 204, 204));
        jPasswordField1.setForeground(new java.awt.Color(0, 0, 0));
        jPasswordField1.setText("jPasswordField1");
        jPasswordField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setFont(new java.awt.Font("sansserif", 3, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("Datos incorrectos");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/images.png"))); // NOI18N

        jLabel5.setText("Iniciar Sesión");

        btnSignIn.setText("Sign In");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(348, 348, 348))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(384, 384, 384))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(356, 356, 356))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btnSignIn)
                        .addGap(391, 391, 391))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(285, 285, 285)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField1)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 333, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(jLabel5)
                .addGap(29, 29, 29)
                .addComponent(jLabel4)
                .addGap(25, 25, 25)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSignIn)
                .addContainerGap(194, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(87, 106, 202));
        jPanel3.setAlignmentX(0.1F);
        jPanel3.setAlignmentY(0.1F);
        jPanel3.setMaximumSize(new java.awt.Dimension(150, 690));
        jPanel3.setMinimumSize(new java.awt.Dimension(150, 690));
        jPanel3.setPreferredSize(new java.awt.Dimension(150, 690));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel3MousePressed(evt);
            }
        });
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_3.setBackground(new java.awt.Color(87, 106, 202));
        btn_3.setMaximumSize(new java.awt.Dimension(150, 43));
        btn_3.setMinimumSize(new java.awt.Dimension(150, 43));
        btn_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                NavLablMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                NavLablMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_3MousePressed(evt);
            }
        });

        ind_3.setBackground(new java.awt.Color(255, 136, 0));
        ind_3.setForeground(new java.awt.Color(255, 136, 0));
        ind_3.setOpaque(false);
        ind_3.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_3Layout = new javax.swing.GroupLayout(ind_3);
        ind_3.setLayout(ind_3Layout);
        ind_3Layout.setHorizontalGroup(
            ind_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_3Layout.setVerticalGroup(
            ind_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        lblNavCaja.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblNavCaja.setForeground(new java.awt.Color(255, 255, 255));
        lblNavCaja.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblNavCaja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Water_25px.png"))); // NOI18N
        lblNavCaja.setText("Salir");
        lblNavCaja.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblNavCaja.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                NavLablMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                NavLablMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_3MousePressed(evt);
            }
        });

        javax.swing.GroupLayout btn_3Layout = new javax.swing.GroupLayout(btn_3);
        btn_3.setLayout(btn_3Layout);
        btn_3Layout.setHorizontalGroup(
            btn_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_3Layout.createSequentialGroup()
                .addComponent(ind_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(lblNavCaja, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );
        btn_3Layout.setVerticalGroup(
            btn_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_3Layout.createSequentialGroup()
                .addGroup(btn_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ind_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(btn_3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblNavCaja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(0, 7, Short.MAX_VALUE))
        );

        jPanel3.add(btn_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 640, 150, 50));

        btn_1.setBackground(new java.awt.Color(87, 106, 202));
        btn_1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_1.setMaximumSize(new java.awt.Dimension(150, 43));
        btn_1.setMinimumSize(new java.awt.Dimension(150, 43));
        btn_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                NavLablMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                NavLablMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_1MousePressed(evt);
            }
        });

        ind_1.setBackground(new java.awt.Color(255, 136, 0));
        ind_1.setForeground(new java.awt.Color(255, 136, 0));
        ind_1.setOpaque(false);
        ind_1.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_1Layout = new javax.swing.GroupLayout(ind_1);
        ind_1.setLayout(ind_1Layout);
        ind_1Layout.setHorizontalGroup(
            ind_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_1Layout.setVerticalGroup(
            ind_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        lblNavInicio.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblNavInicio.setForeground(new java.awt.Color(255, 255, 255));
        lblNavInicio.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblNavInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Contacts_25px.png"))); // NOI18N
        lblNavInicio.setText("Iniciar Sesión");
        lblNavInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblNavInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                NavLablMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                NavLablMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout btn_1Layout = new javax.swing.GroupLayout(btn_1);
        btn_1.setLayout(btn_1Layout);
        btn_1Layout.setHorizontalGroup(
            btn_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_1Layout.createSequentialGroup()
                .addComponent(ind_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNavInicio, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                .addContainerGap())
        );
        btn_1Layout.setVerticalGroup(
            btn_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_1Layout.createSequentialGroup()
                .addComponent(ind_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(btn_1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNavInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.add(btn_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 150, 43));

        jLabel29.setBackground(new java.awt.Color(0, 0, 0));
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/favicon1.png"))); // NOI18N
        jLabel29.setOpaque(true);
        jPanel3.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 100));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 1120, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void NavLablMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NavLablMouseEntered
        // TODO add your handling code here:
        
        paintLblMouseEntered_Exited(evt,"in");


    }//GEN-LAST:event_NavLablMouseEntered

    private void NavLablMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NavLablMouseExited
        // TODO add your handling code here:
         paintLblMouseEntered_Exited(evt,"out");
    }//GEN-LAST:event_NavLablMouseExited


    private void btn_1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_1MousePressed
        // TODO add your handling code here:
        setColor(btn_1, lblNavInicio);
        ind_1.setOpaque(true);
        resetColor(new JPanel[]{btn_3}, new JPanel[]{ind_3}, new JLabel[]{lblNavCaja});

        jPanel2.setVisible(true);
        panelWelcome.setVisible(false);

    }//GEN-LAST:event_btn_1MousePressed

    private void btn_3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_3MousePressed
        // TODO add your handling code here:
        setColor(btn_3, lblNavCaja);
        ind_3.setOpaque(true);
        resetColor(new JPanel[]{btn_1}, new JPanel[]{ind_1}, new JLabel[]{lblNavInicio});

        System.exit(0);
    }//GEN-LAST:event_btn_3MousePressed

    private void jPanel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MousePressed
        // TODO add your handling code here:
        resetNavPanel();
    }//GEN-LAST:event_jPanel3MousePressed

    // int xx, xy;
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Windows".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(FrmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(FrmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(FrmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FrmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new FrmInicio().setVisible(true);
//            }
//        });
//    }

    private void setColor(JPanel pane, JLabel lbl) {
        pane.setBackground(new Color(41, 57, 80));
        lbl.setForeground(new Color(255, 255, 255));
        lbl.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        // TODO add your handling code here:
    }

    private void resetColor(JPanel[] pane, JPanel[] indicators, JLabel[] labels) {
        for (int i = 0; i < pane.length; i++) {
            pane[i].setBackground(new Color(87, 106, 202));

        }

        for (int i = 0; i < indicators.length; i++) {
            indicators[i].setOpaque(false);
        }

        for (int i = 0; i < labels.length; i++) {
            labels[i].setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        }

    }

    //Metodo que RESETA las pestañas y establece la PANTALLA de WELCOME 
    private void resetNavPanel() {

        resetColor(new JPanel[]{btn_3, btn_1}, new JPanel[]{ind_3, ind_1}, new JLabel[]{lblNavCaja, lblNavInicio});

        panelWelcome.setVisible(true);
        jPanel2.setVisible(false);

    }
    
    
    
    
        private void paintLblMouseEntered_Exited( MouseEvent evt, String str) {
            
            Color color= Color.WHITE;
            
            if (str.equalsIgnoreCase("in")){
                color= Color.RED;
            }
            
            
        try {
            JLabel lbl = (JLabel) evt.getSource();

            //Si el indice NO Se ESTA MOSTRANDO (no está seleccionada esta pestaña) y se corresponde a la etiqueta, se cambiará de color, en caso contrario no hará nada
            if (ind_1.isOpaque() == false && lbl.getText().equals("Iniciar Sesión") || lbl.getText().equals("Salir") || evt.getSource().equals(btn_3)) {
                lbl.setForeground(color);
            } else if (ind_3.isOpaque() == false && lbl.getText().equals("Salir") || evt.getSource().equals(btn_3)) {
                lbl.setForeground(color);
            }

        } catch (Exception e) {

            //Si el indice NO Se ESTA MOSTRANDO (no está seleccionada esta pestaña) y se corresponde a la etiqueta, se cambiará de color, en caso contrario no hará nada
            if (ind_1.isOpaque() == false && evt.getSource().equals(btn_1)) {
                lblNavInicio.setForeground(color);
                
            } else if ( ind_3.isOpaque() == false && evt.getSource().equals(btn_3)) {
                lblNavCaja.setForeground(color);
            }

        }
    }//Fin de PaintLblSelected
    
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSignIn;
    private javax.swing.JPanel btn_1;
    private javax.swing.JPanel btn_3;
    private javax.swing.JPanel ind_1;
    private javax.swing.JPanel ind_3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblNavCaja;
    private javax.swing.JLabel lblNavInicio;
    // End of variables declaration//GEN-END:variables

    

    
    
    
}
